db/migrate/20160413202246_add_issues.rb, db/migrate/20160413202258_add_pages.rb
Add Issues and Pages table structures
=> Add Migrations

db/migrate/20160413202246_add_issues.rb, db/schema.rb
Change text to string for hathitrust field as per @gordonleacock suggestion.
=> Add Migrations to db schema

app/assets/stylesheets/blacklight/_header.scss, app/views/catalog/_home_text.html.erb, app/views/shared/_header_navbar.html.erb, config/locales/blacklight.en.yml
Remove blacklight views and update  header
=> Remove blacklight views

.gitignore, app/controllers/catalog_controller.rb
Remove default search fields from catalog controller
=> Remove blacklight default fields

ISSUE_TEMPLATE.md
Basic Template for creating issues
=> Add Issue Template

ISSUE_TEMPLATE.md
=> Update Template file

app/models/issue.rb, app/models/page.rb, solr/conf/_rest_managed.json, solr/conf/admin-extra.html, solr/conf/elevate.xml, solr/conf/mapping-ISOLatin1Accent.txt, solr/conf/protwords.txt, solr/conf/schema.xml, solr/conf/scripts.conf, solr/conf/solrconfig.xml, solr/conf/spellings.txt, solr/conf/stopwords.txt, solr/conf/stopwords_en.txt, solr/conf/synonyms.txt
Add models and Solr indexing support for blacklight-core
=> Add models and Solr indexing support

.gitignore, app/controllers/catalog_controller.rb, app/models/issue.rb, app/models/page.rb
index page fields in solr
Ignore byebug history
=> update page model to save solr doc

app/controllers/catalog_controller.rb, app/helpers/application_helper.rb, app/models/page.rb, app/views/catalog/_index_header_default.html.erb, app/views/catalog/_show_sidebar.html.erb, app/views/catalog/_show_tools.html.erb, app/views/catalog/show.html.erb
=> Add display fields

app/controllers/catalog_controller.rb, app/models/page.rb
=> Add keyword search

app/controllers/catalog_controller.rb
Put in some default values for highlighting configuration; make sure to change
when accessibility information comes back.
=> Add options to catalog_controller to control highlighting

app/helpers/application_helper.rb, app/indexers/issue_indexer.rb, app/indexers/page_indexer.rb, app/models/page.rb, lib/tasks/fishrappr.rake, lib/tasks/populate_fake_data.rake
Move indexing out of Page model, and include page navigation.
Attempt to make fake data more useful for development: pages are colored by issue; image labels are reflect issue/sequence context.
=> Index page navigation

app/views/catalog/_index_header_default.html.erb, app/views/catalog/_thumbnail_default.html.erb
On the way to matching Trevor's layout.
=> add thumbnail template for list view

app/helpers/application_helper.rb, app/views/catalog/_show_default.html.erb
=> Highlight search keyword on page display

app/controllers/catalog_controller.rb
=> Configure wildcard search

Gemfile, Gemfile.lock, app/assets/stylesheets/static.scss, app/controllers/catalog_controller.rb, app/views/shared/nav/_contact.html.erb, app/views/static/contact.html.erb, config/initializers/simple_form.rb, config/locales/en.yml, config/locales/simple_form.en.yml, lib/templates/erb/scaffold/_form.html.erb
contact page (still ugly)
This is before visual clean up and accessibility changes
=> contact form start

app/controllers/catalog_controller.rb, app/helpers/range_limit_helper.rb, app/views/blacklight_range_limit/_range_limit_panel.html.erb, app/views/blacklight_range_limit/_range_segments.html.erb
Update widget: change max length and move slider below the graph
=> Update date range widget

app/services/daily_xml_to_db_v2.rb, config/application.rb, lib/tasks/data/daily_xml_to_db.rake
**revise xml import per Roger's tables**
**I couldn't get the following code to work. Error was "NoMethodError: undefined method `title=' for nil:NilClass"** I would have tried to add to the model but wasn't sure what if anything I needed to do with an indexer.
def add_daily_publication
p = Publication.find_or_create_by(slug: "the-michigan-daily") do |publication|
p.title = "The Michigan Daily"
p.info_link = "https://michigandaily.com"
p.save # not sure if I need this, prob. not...
end
p.id
end
**Also, could not get overall METS prefix for @doc to work. Back to adding the namespace to the file for now.**
=> update xml import

app/assets/stylesheets/blacklight.scss, app/controllers/catalog_controller.rb
- highlight with orange
- show more snippets in results views
- make separation of snippets more obvious ('...' vs. space)
=> minor updates to search results

app/assets/stylesheets/grid.scss, app/controllers/catalog_controller.rb, app/controllers/concerns/fishrappr/catalog.rb, app/helpers/application_helper.rb, app/indexers/page_indexer.rb, app/views/catalog/_show_default.html.erb, lib/tasks/populate_fake_data.rake
If we have to tweak how page_text is indexed, we can change the schema definition instead of all these code points.
=> store full text in page_text property

app/assets/javascripts/application.js, app/assets/javascripts/static.js, app/assets/stylesheets/custom.css.scss, app/controllers/catalog_controller.rb, app/helpers/range_limit_helper.rb, app/views/catalog/_search_form.html.erb, app/views/catalog/home.html.erb
Interim fix while we wait for the real thing.
=> add rotating wait icon to search button

app/assets/stylesheets/custom.css.scss, app/views/catalog/home.html.erb, config/initializers/simple_form.rb
Also includes:
- A magnifying glass icon on home and catalog searches
- Change to app/helpers/range_limit_helper.rb to prevent crash when solr is empty
=> add home page style search form to catalog page

Gemfile, app/assets/stylesheets/custom.css.scss, app/views/catalog/home.html.erb, app/views/contacts/new.html.erb, config/initializers/simple_form.rb, config/locales/simple_form.en.yml
updated config/initializers/simple_form.rb
update contacts per rdr
=> add home page search to catalog page

app/assets/javascripts/results_page_highlighting.js, app/assets/stylesheets/blacklight.scss, app/controllers/catalog_controller.rb, app/controllers/concerns/fishrappr/catalog.rb, app/controllers/services_api_controller.rb, app/controllers/static_controller.rb, app/helpers/application_helper.rb, app/indexers/issue_indexer.rb, app/models/document_search_builder.rb, app/models/search_builder.rb, app/services/daily_xml_to_db_v2.rb, app/views/_user_util_links.html.erb, app/views/catalog/_index_grid.html.erb, app/views/catalog/_index_header_default.html.erb, app/views/catalog/_show_image.html.erb, app/views/catalog/show.html.erb, app/views/services_api/annotations.json.jbuilder, app/views/services_api/manifests.json.jbuilder, config/application.rb, config/routes.rb, lib/tasks/data/daily_xml_to_db.rake, solr/conf/schema.xml
page highlighting on issues
simplifying format of coordinate packed data
search highlighting on results pages + toggle between publications
page abstract; refine fields; tweak oversizing of search highlights
=> search highlights on images

app/assets/javascripts/leaflet-iiif.js, app/assets/javascripts/leaflet.remote_zoom.js, app/helpers/application_helper.rb, app/views/catalog/_show_image.html.erb, app/views/catalog/show.html.erb, config/locales/en.yml, public/extra/leaflet-iiif.js
- move zoom controls outside of viewer + add labels + zoom status
- add page number to page navigation
=> iterating on page navigation

app/models/contact.rb, config/application.rb
Also adds config for the two address in application.rb
=> add second contact address for permissions

app/assets/javascripts/toggle_highlighting.js, app/assets/stylesheets/blacklight.scss, app/controllers/concerns/fishrappr/catalog.rb, app/helpers/application_helper.rb, app/views/catalog/_show_image.html.erb, app/views/catalog/show.html.erb, config/routes.rb
Adds preliminary support for toggling hit highlighting.
See #114 for details.
=> support for toggling hit highlighting for text and images

app/assets/javascripts/static.js, app/assets/stylesheets/custom.css.scss, app/views/catalog/_search_form.html.erb, app/views/catalog/home.html.erb, config/locales/en.yml
**_Changes:_**
1. Improve look and interaction of search box
2. DRY search code in view/catalog/_search_form.html.erb
=> add improved interactivity to search

app/controllers/catalog_controller.rb, app/helpers/application_helper.rb
=> change highlight delimiters for better HTML escaping

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/assets/javascripts/downloader.js.erb, app/assets/stylesheets/viewer.scss, app/controllers/concerns/fishrappr/catalog.rb, app/helpers/application_helper.rb, app/views/catalog/_document.html.erb, app/views/catalog/show.html.erb, config/application.rb, config/routes.rb
- arrange download options
- download issue
- download page PDF
- download page image [needs work]
=> enable download options

app/assets/javascripts/static.js, app/assets/stylesheets/custom.css.scss, app/views/catalog/_footer.html.erb, app/views/catalog/home.html.erb, app/views/contacts/new.html.erb, app/views/layouts/application.html.erb, app/views/layouts/home.html.erb, app/views/static/_about_sidebar.html.erb, app/views/static/_help_sidebar.html.erb, app/views/static/_help_sidebar_link.erb, app/views/static/_unified_sidebar.html.erb, app/views/static/about.html.erb, app/views/static/how_to_search.html.erb
update help about page formats and links
=> add footer to all pages; update help & about page formats and links

app/assets/stylesheets/_globals.scss, app/assets/stylesheets/custom.css.scss, app/assets/stylesheets/viewer.scss, app/views/catalog/show.html.erb, config/locales/blacklight.en.yml
First pass at implementing latest page viewer:
- Page actions definitely needs re-working
- need to add issue search
=> rearranged buttons; fitting in everything

app/assets/javascripts/application.js, app/assets/javascripts/browse.js, app/assets/javascripts/static.js, app/assets/stylesheets/application.css, app/assets/stylesheets/custom.css.scss, app/controllers/catalog_controller.rb, app/controllers/concerns/fishrappr/catalog.rb, app/helpers/application_helper.rb, app/models/search_builder.rb, app/views/catalog/_home_header_navbar.html.erb, app/views/catalog/_search_form.html.erb, app/views/catalog/home.html.erb, config/locales/blacklight.en.yml, config/routes.rb, lib/fishrappr/controller_override.rb
Changes to re-do search form and remove dependency on blacklight range search gem.
=> great but not if constraints do not work

app/assets/javascripts/browse.js, app/controllers/catalog_controller.rb, app/views/shared/nav/_browse.html.erb, config/routes.rb
add back browse menu item
restore menu link to browse and improve browse js
=> add browse route

app/assets/stylesheets/custom.css.scss, app/controllers/catalog_controller.rb, app/helpers/application_helper.rb, app/views/catalog/_search_form.html.erb, app/views/shared/_header_navbar.html.erb
cleanup months; remove padding between cells
=> fix month presentation in facets

app/assets/javascripts/results_page_highlighting.js, app/assets/stylesheets/custom.css.scss, app/assets/stylesheets/grid.scss, app/controllers/concerns/fishrappr/catalog.rb, app/helpers/blacklight_helper.rb, app/views/catalog/browse.html.erb, app/views/catalog/home.html.erb
- `home` controller gathered 3 random documents from today, or utterly random if that fails
- `home` view builds gallery and sets up browse link with today's month/day
- `browse` form uses incoming parameters to fill the form
- `browse` will use the current publication
=> building on gordonl's sketch

app/assets/javascripts/results_page_highlighting.js, app/assets/stylesheets/blacklight.scss, app/assets/stylesheets/custom.css.scss, app/assets/stylesheets/grid.scss, app/controllers/concerns/blacklight/default_component_configuration.rb, app/controllers/concerns/fishrappr/catalog.rb, app/helpers/application_helper.rb, app/views/catalog/_document.html.erb, app/views/catalog/_document_header.html.erb, app/views/catalog/_results_pagination.html, app/views/catalog/browse.html.erb, config/application.rb, config/locales/blacklight.en.yml
- add search highlighting to thumbnails on list view
- search uses list view
- list view converges closer to mockups
- browse uses grid
=> updates to views

app/assets/stylesheets/graph.scss, app/controllers/concerns/fishrappr/catalog.rb, app/helpers/application_helper.rb, app/views/catalog/show.html.erb, config/locales/blacklight.en.yml
@roger: Okay, I'm not sure why come graph-related changes came through here.
=> Browse cleanup

app/assets/javascripts/graph_in_sidebar.js, app/assets/stylesheets/custom.css.scss, app/assets/stylesheets/graph.scss, app/helpers/application_helper.rb, app/helpers/blacklight/layout_helper_behavior.rb, app/views/catalog/_fishrappr_panel.html.erb, app/views/catalog/_search_graph.html.erb, app/views/catalog/_search_sidebar.html.erb, app/views/catalog/index.html.erb
add graph axis labels; auto-adjust for y axis label for graph height
=> improve graph labeling

app/helpers/application_helper.rb, app/services/daily_xml_to_db_v2.rb
track schema.rb
graph changes plus other fixes
small change in xml import
issue #186
=> graphC - add clicking down to one day shown in graph

app/controllers/concerns/fishrappr/catalog.rb, app/helpers/application_helper.rb
fix first page sequence reference (sequence:1 to issue_sequence:1)
fix blank search presentation to truncate the full "highlighted" text
=> various fixes

app/assets/stylesheets/custom.css.scss, app/assets/stylesheets/grid.scss, app/views/catalog/browse.html.erb, app/views/static/_unified_sidebar.html.erb, app/views/static/about.html.erb, app/views/static/donors.html.erb, app/views/static/how_to_search.html.erb
Please review issue #162 for comments
=> update doc outlines

app/controllers/concerns/fishrappr/catalog.rb, app/helpers/application_helper.rb, app/views/catalog/_search_form.html.erb
=> issue #201 hide date option when using facets

app/views/catalog/_search_form.html.erb
update and simplify catalog/_search_form.html.erb
=> update and simplify catalog/_search_form.html.erb

app/assets/javascripts/results_page_highlighting.js
=> restore results highlighting for thumbnail; make compatible with wide pages

app/assets/javascripts/static.js, app/assets/stylesheets/custom.css.scss, app/views/catalog/show.html.erb, config/locales/en.yml
improve home page per Bentley
add back-to-top to show page
=> add back-to-top to show page

app/assets/stylesheets/blacklight.scss, app/assets/stylesheets/bootstrap-overrides.scss, app/assets/stylesheets/bootstrap-variables.scss, app/assets/stylesheets/fishrappr.scss, app/assets/stylesheets/modules/buttons.scss, app/assets/stylesheets/modules/custom.scss, app/assets/stylesheets/modules/viewer.scss, app/helpers/application_helper.rb, app/helpers/catalog_helper.rb, app/helpers/zzzzzz_helper.rb, app/views/catalog/_show_default.html.erb, app/views/catalog/show.html.erb, config/locales/blacklight.en.yml, config/locales/en.yml
https://app.zeplin.io/project.html#pid=57f69abd267208f65efa3e09&sid=57f69f40c94a5e41575ce2a6
AND: fix rendering of constraints in title
AND: probably include files that were forgotten in the last PR, sigh
=> update design to match latest UX

.gitignore, Gemfile, Gemfile.lock, app/assets/javascripts/page_image_viewer.js, app/assets/javascripts/results_page_highlighting.js, app/assets/stylesheets/modules/buttons.scss, app/controllers/concerns/fishrappr/context.rb, app/helpers/application_helper.rb, app/models/contact.rb, app/models/search_builder.rb, app/services/repository_service.rb, app/views/catalog/_document.html.erb, app/views/catalog/index.html.erb, app/views/catalog/show.html.erb, app/views/layouts/application.html.erb, config/application.rb, config/initializers/config.rb, config/settings.yml
Abstract repository access to RepositoryService module; remove explicit references to hathitrust; update image helpers. Try to make the abstractions better available to javascript.
This PR introduces a settings.yml for the application; application.rb values have been moved here.
Requires the DLXS_SERVICE_URL repository host to be defined in settings.local.yml.
Does not update indexing.
=> configure repository for preview.quod

app/assets/stylesheets/modules/custom.scss, app/views/layouts/application.html.erb
Enable by running with `DEBUG_CSS=1 bundle exec rails s`
=> add responsive debugging

app/controllers/catalog_controller.rb, app/helpers/application_helper.rb
- added sort by relevance configuration ("Sort by Interesting")
- disabled sort by image number 
- updated issue link to sort by relevance
=> disable sort-by-number; enable sort-by-score

app/assets/stylesheets/modules/buttons.scss, app/assets/stylesheets/modules/viewer.scss, app/helpers/application_helper.rb, app/views/catalog/_document_share_metadata.html.erb, app/views/catalog/_show_header_default.html.erb, app/views/catalog/show.html.erb, config/locales/blacklight.en.yml, config/locales/en.yml
- fixes for the sm breakpoint
- twitter/facebook metadata
- tuning
=> tweaking page view layout

app/assets/stylesheets/modules/custom.scss, app/views/contacts/new.html.erb, app/views/static/_unified_sidebar.html.erb, app/views/static/about_daily.html.erb, app/views/static/about_project.html.erb, app/views/static/donors.html.erb, app/views/static/faq.html.erb, app/views/static/how_to_search.html.erb, app/views/static/using_page_viewer.html.erb
Did a major cleanup of help.
- Update help to be responsive
- This is an intermediate version while working with D&D on content.
- It is very plain and will need new styling
=> update help to be responsive

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/assets/javascripts/page_image_viewer.js, app/assets/javascripts/static.js, app/assets/stylesheets/application.scss, app/assets/stylesheets/modules/viewer.scss, app/controllers/catalog_controller.rb, app/helpers/application_helper.rb, app/views/catalog/_document_header.html.erb, app/views/catalog/_image_viewer_toolbar_bottom.html.erb, app/views/catalog/_image_viewer_toolbar_top.erb, app/views/catalog/show.html.erb, config/locales/blacklight.en.yml, config/locales/en.yml
- add font awesome for more awesome icons
- image viewer sports a top and bottom toolbar for more effective use of screen real estate
- update issue titles (completeness, responsiveness)
=> font-awesome + toolbars

app/assets/stylesheets/modules/custom.scss, app/assets/stylesheets/modules/graph.scss, app/views/catalog/_fishrappr_panel.html.erb, app/views/catalog/_search_graph.html.erb, app/views/catalog/index.html.erb, config/locales/blacklight.en.yml, config/locales/en.yml
NOTES:
1. - Graph doesn't full match Trevor's mock up (no gray backgrounds at 100% width)
2. - Facet headers hidden with width and height zero instead of a code change
=> add search results sidebar fixes

Gemfile, Gemfile.lock, app/controllers/concerns/fishrappr/catalog.rb, app/helpers/application_helper.rb, app/indexers/issue_indexer.rb, app/indexers/page_indexer.rb, app/models/issue.rb, app/services/dlxs_ingest.rb, app/services/repository_service.rb, app/views/catalog/home.html.erb, app/views/catalog/show.html.erb, config/routes.rb, config/settings.yml, db/migrate/20160413202246_add_issues.rb, db/migrate/20160413202258_add_pages.rb, db/schema.rb, lib/fishrappr/search_state.rb, lib/tasks/fishrappr.rake
ingest from DLXS + even more SEO friendly URLs
=> rebuild for updated IIIF API

app/indexers/page_indexer.rb, app/services/dlxs_ingest.rb, app/services/repository_service.rb, lib/tasks/fishrappr.rake
Speed up ingest at the expense of validation (look into that later).
Deal with indexing pages with no full text.
=> speed up data load

app/controllers/concerns/fishrappr/catalog.rb, app/views/catalog/issue_download_readme.txt.erb, config/locales/en.yml
- Configure rights statement
- update zip colophon to text template to better format rights statement text
=> install rights statement

app/assets/javascripts/downloader.js.erb, app/assets/stylesheets/modules/modals.scss, app/assets/stylesheets/modules/viewer.scss, app/services/repository_service.rb, app/views/shared/_footer.html.erb
Support changes to how multi-page PDF building works in DLXS.
=> Pdf mayhem

app/assets/javascripts/page_image_viewer.js, app/assets/stylesheets/fishrappr.scss, app/assets/stylesheets/modules/custom.scss, app/assets/stylesheets/modules/flash.scss, app/assets/stylesheets/modules/viewer.scss, app/controllers/application_controller.rb, app/controllers/catalog_controller.rb, app/controllers/sessions_controller.rb, app/helpers/application_helper.rb, app/models/user.rb, app/services/repository_service.rb, app/views/_flash_msg.html.erb, app/views/_user_util_links.html.erb, app/views/catalog/_image_viewer_toolbar_bottom.html.erb, app/views/catalog/_show_sidebar.html.erb, app/views/catalog/_show_viewer_stacked_tabs.html.erb, app/views/layouts/application.html.erb, app/views/layouts/pageview.html.erb, app/views/sessions/login_info.html.erb, app/views/static/using_page_viewer.html.erb, config/application.rb, config/environments/development.rb, config/environments/test.rb, config/locales/en.yml, config/routes.rb, lib/devise/behaviors/http_header_authenticatable_behavior.rb, lib/devise/fake_auth_header.rb, lib/devise/models/http_header_authenticatable.rb, lib/devise/strategies/http_header_authenticatable.rb
Add login support to fishrappr.
=> Auth support

app/assets/stylesheets/fishrappr.scss, app/assets/stylesheets/modules/custom.scss, app/assets/stylesheets/modules/flash.scss, app/assets/stylesheets/modules/login_info.scss, app/assets/stylesheets/modules/viewer.scss, app/views/catalog/_show_sidebar.html.erb, app/views/catalog/browse.html.erb, app/views/layouts/application.html.erb, app/views/layouts/blacklight.html.erb, app/views/layouts/pageview.html.erb, app/views/layouts/static.html.erb, app/views/sessions/login_info.html.erb, app/views/shared/_header_navbar.html.erb, app/views/static/rights.html.erb, config/locales/en.yml
=> Mostly update text for "Why Log In?" and the Rights statement

app/assets/javascripts/search_history_support.js
Maybe modify the javascript tracking search actions to be aware of the new routing structure. SIgh.
=> account for new publication route

app/views/publications/djnews/views/static/project.html.erb, config/locales/en.yml
See history in Bentley slack channel.
=> add quick fixed for Bentley to home and about project pages

app/assets/javascripts/graph_in_sidebar.js, app/helpers/application_helper.rb
Code change in application_helper.rb:
deleted:
this_range = (189..201).map { |d| d * 10}
added:
decade_first_div_10 = @publication.first_print_year/10.truncate
decade_last_div_10 = @publication.last_print_year/10.truncate
this_range = (decade_first_div_10..decade_last_div_10).map { |d| d * 10}
=> change from fixed midaily dates to @publication. print years for decades

app/views/publications/djnews/views/static/rights.html.erb
Added the proposed DJN right statement
=> add updated djnews rights statement

app/assets/stylesheets/modules/custom.scss, app/views/publications/djnews/views/catalog/home.html.erb, config/locales/en.yml
Modified:
-- djnews home page head description text and width
-- djnews home page donor anchor width
=> update home page descriptions per Max at Bentley

db/migrate/20180817173811_seed_publication_print_years.rb, lib/tasks/fishrappr.rake
Migration to seed the publication dates from existing data.
(And some updates to the rake tasks that load/index data.)
=> seed publication dates

Gemfile, Gemfile.lock
Fixes security problem with sprockets gem
=> fix security problem with sprockets gem

app/helpers/application_helper.rb, app/services/repository_service.rb
=> update PDF downloads to work with multiple publications/collections

app/views/publications/djnews/views/_user_util_links.html.erb, app/views/publications/djnews/views/shared/nav/_about.html.erb, app/views/publications/djnews/views/shared/nav/_help.html.erb, app/views/publications/djnews/views/static/about.html.erb, app/views/publications/midaily/views/_user_util_links.html.erb, config/routes.rb
Got more complex that I expected:
get '/static/donors', action: :show, publication: 'midaily', controller: 'static', page: 'donors'
get '/static/about_project', action: :show, publication: 'midaily', controller: 'static', page: 'project'
get '/static/daily_about', action: :show, publication: 'midaily', controller: 'static', page: 'about'
get '/static/rights', action: :show, publication: 'midaily', controller: 'static', page: 'rights'
get '/static/how_to_search', action: :show, publication: 'midaily', controller: 'static', page: 'how_to_search'
get '/static/using_page_viewer', action: :show, publication: 'midaily', controller: 'static', page: 'using_page_viewer'
=> redirect old static links to new daily locations

Gemfile, Gemfile.lock, config/sitemap.rb
...and refactor the weird issue caching.
=> update sitemap generation to include djnews publication

app/controllers/application_controller.rb, app/controllers/concerns/fishrappr/context.rb, app/controllers/sessions_controller.rb, app/controllers/static_controller.rb, app/helpers/application_helper.rb, app/views/layouts/application.html.erb, lib/fishrappr/controller_override.rb
Clean up various puts commands.
=> removed unneed puts commands

app/assets/stylesheets/modules/custom.scss
Possibly in the running for the nitpickiest PR this spring...
=> fix mastheads so they scale properly for mobile

app/assets/stylesheets/modules/custom.scss, app/views/publications/djnews/views/catalog/home.html.erb, app/views/publications/midaily/views/catalog/home.html.erb
Switch to fixed width logos in partnership section of home page
Maintain consistent heading sizes in partnership section of home page
=> djn-add-logo-fixed-widths

app/views/publications/djnews/views/catalog/home.html.erb, app/views/publications/midaily/views/catalog/home.html.erb
Clumsy PR for logos on home pages.
=> production fix up for logo using link_to and image_tag

app/views/publications/djnews/views/catalog/_home_text.html.erb, app/views/publications/djnews/views/static/about.html.erb, app/views/publications/djnews/views/static/donors.html.erb
- Update text of djnews about page
- Update text of donors about page; split into two paragraphs
- Add suggested searches from Max
=> add donor pages and suggested searches

app/views/publications/djnews/views/catalog/home.html.erb, config/locales/en.yml
modified:   app/views/publications/djnews/views/catalog/home.html.erb - removed description2 paragraph
modified:   config/locales/en.yml - modified description text based on Max's request:
UPDATE: “The Detroit Jewish News has been serving Metro Detroit’s Jewish community since 1942”
=> shortened description text

Gemfile, app/controllers/contacts_controller.rb, app/models/contact.rb, app/views/catalog/_document_share_metadata.html.erb, app/views/contacts/new.html.erb, config/environments/development.rb
- parameterize site name for social metadata and contact form
- update loofah gem version
=> Publication label issues

app/views/publications/djnews/views/static/how_to_search.html.erb, app/views/publications/midaily/views/static/how_to_search.html.erb
DJN should now have a section "Too Many Search Results" and Daily should have Proximity Searches, responding to the expressed needs/desires of their communities
=> Update "How to Search" pages

app/views/publications/djnews/views/static/how_to_search.html.erb, app/views/publications/midaily/views/static/donors.html.erb
=> Updating donors

Gemfile, Gemfile.lock, app/controllers/contacts_controller.rb, app/views/contacts/new.html.erb, config/initializers/new_google_recaptcha.rb, config/settings.yml
Add `new_google_recaptcha`, based on Deep Blue Data work.
=> MAINTAIN-32: add recaptcha to contact forms
