- app/services/daily_xml_to_db.rb
- lib/tasks/data/daily_xml_to_db.rake
**Rake Task to import daily xml via active record**
Closes issue #29 
daily_xml_to_db v1
updating xml import
remove issue_no from pages create call
Gets xml files from directory tmp/xml_data
To use: _bundle exec rake data:daily_xml_to_db --trace_
Lots of output for now; to reduce to one line of output per file alter lib/task/data/daily_xml_to_db.rake L7, change "testing" to something else, like "not_testing".
> rake task daily_xml_to_db

- Gemfile
- Gemfile.lock
- app/assets/javascripts/static.js
- app/assets/stylesheets/static.scss
- app/controllers/static_controller.rb
- app/helpers/application_helper.rb
- app/helpers/static_helper.rb
- app/models/page.rb
- app/views/static/page.html.erb
- app/views/static/test.html.erb
- config/application.rb
- config/routes.rb
- lib/tasks/fishrappr.rake
- test/controllers/static_controller_test.rb
Added hathitrust_image and hathitrust_thumbnail helpers to setup image references from the solr document.
Added `hathitrust` identifier to page solr document.
Added rake task to reindex pages (`rake fishrappr:reindex_pages`).
- added pry
- added puma
- remove coffeescript
> Start of helpers to pull image derivatives from HathiTrust imgsrv.

- .gitignore
- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js
- app/helpers/application_helper.rb
- app/models/page.rb
- config/application.rb
- lib/tasks/fishrappr.rake
- lib/tasks/populate_fake_data.rake
Added tasks and support for fake data.
To make this efficient, added configuration options to `application.rb` which we will need to revisit with proper configuration options. Mostly this allows for **disabling indexing** and **managing solr commits** which can speed up data loads immensely.
> tasks + helpers for using fake data

- app/controllers/catalog_controller.rb
WIP - Solr returns the highlighted text as italicized, and it truncates the text to show only the highlighted text line
> Add Solr Hit Highlight feature

- Gemfile.lock
- app/controllers/catalog_controller.rb
- app/controllers/concerns/fishrappr/catalog.rb
- app/helpers/application_helper.rb
- app/helpers/zzzzzz_helper.rb
- app/indexers/issue_indexer.rb
- app/indexers/page_indexer.rb
- app/presenters/fishrappr/document_presenter.rb
- app/views/catalog/show.html.erb
- config/application.rb
- config/locales/en.yml
- config/routes.rb
- lib/fishrappr/search_state.rb
- solr/conf/schema.xml
- solrdoc paths default to /browse/:issue_date/:sequence
- adds support for calculating next_page and previous_page within the issue
- adds previous page/previous page when viewing pages
YOU WILL NEED TO REINDEX PAGES AGAINST A FRESH SOLR INDEX: `bundle exec rake fishrappr:reindex_pages`
> initial attempts at hacking the paths

- app/assets/stylesheets/grid.scss
- app/controllers/catalog_controller.rb
- app/views/catalog/_document_grid.html.erb
- app/views/catalog/_index_grid.html.erb
- config/locales/blacklight.en.yml
Simple grid view for search results, based on SearchWorks. Stylesheet currently hides the fulltext field pending further investigation.
The number of results has been changed to [ 24, 48, 144 ] to prevent orphan rows in the grid.
> simple grid view

- Gemfile
- app/controllers/catalog_controller.rb
- app/controllers/concerns/fishrappr/catalog.rb
- app/helpers/application_helper.rb
- app/indexers/issue_indexer.rb
- app/indexers/page_indexer.rb
- app/models/issue.rb
- app/models/page.rb
- app/models/publication.rb
- app/views/catalog/_index_grid.html.erb
- config/routes.rb
- db/migrate/20160413200000_create_publications.rb
- db/migrate/20160413202246_add_issues.rb
- db/migrate/20160413202258_add_pages.rb
- db/schema.rb
- lib/fishrappr/search_state.rb
- lib/tasks/populate_fake_data.rake
- solr/conf/schema.xml
- spec/models/publication_spec.rb
Adding support for publications (#60,61,62,63)
index supports tracking publisher; references to issue_date > date_issued; url_for_document uses proposed hierarchical route
issue_date facet should be date_issued
adjust sequence facets
schema.xml has fields specifically for fishrappr (multivalued fields cannot be used for sort).
Closes: #60, #61, #62, #63, #64
> Support for publications, adding barcodes to path, etc.

- app/assets/javascripts/toggle_highlighting.js
- app/controllers/concerns/fishrappr/catalog.rb
- only emply highlight script on show pages
- assume initial state is to show highlights
Addresses part of  #122
> fixes for highlighting

- app/assets/javascripts/leaflet.remote_zoom.js
- app/assets/stylesheets/blacklight.scss
- app/assets/stylesheets/viewer.scss
- app/controllers/concerns/fishrappr/catalog.rb
- app/helpers/application_helper.rb
- app/views/catalog/_document.html.erb
- app/views/catalog/_document_header.html.erb
- app/views/catalog/_document_list.html.erb
- app/views/catalog/_index_default.html.erb
- app/views/catalog/_index_grid.html.erb
- app/views/catalog/_show_header_default.html.erb
- app/views/catalog/_show_image.html.erb
- app/views/catalog/_show_main_content.html.erb
- app/views/catalog/show.html.erb
Views:
- zoom toolbar rearranged based on fultonis feedback
- disable scroll-to-zoom
- indicate focus on image viewer
- render OCR with line breaks + larger font = increased legibility (per futonis)
- begin simplifying layout of list results
Highlighting:
- standardize on #4C7ED1 at 40% for read-through-highlighting
- image highlighting gets less opaque as you zoom in
Temporarily:
- display leaflet zoom level in zoom toolbar
> Update views: simplify, reduce. And highlighting: complexify, obtuse

- Gemfile
- Gemfile.lock
- app/assets/javascripts/leaflet-iiif.js
- app/assets/javascripts/leaflet.remote_zoom.js
- app/assets/javascripts/page_image_viewer.js
- app/assets/javascripts/toggle_highlighting.js
- app/assets/stylesheets/_globals.scss
- app/assets/stylesheets/blacklight/_header.scss
- app/assets/stylesheets/custom.css.scss
- app/assets/stylesheets/viewer.scss
- app/controllers/catalog_controller.rb
- app/controllers/concerns/fishrappr/catalog.rb
- app/views/catalog/_document.html.erb
- app/views/catalog/show.html.erb
- app/views/layouts/application.html.erb
- app/views/layouts/blacklight.html.erb
- app/views/layouts/pageview.html.erb
- app/views/shared/_footer.html.erb
- app/views/shared/_header_navbar.html.erb
Lots of changes:
- application.html.erb is the core layout; other layouts extend it, replacing the slots as necessary
-- @gordonleacock - the home page uses the body class blacklight-catalog-home now
- added _globals.scss to collect common design values (background colors, font stacks, etc)
- migrated the footer to shared/footer, vs. all layouts pulling from catalog/footer
- coded footer more like a bootstrap nav; moved the copyright under the footer as in mockups
This also is the first pass at reworking the pageview page; nestive whacking forced its early release.
> round of edit to views

- app/assets/javascripts/downloader.js.erb
- app/controllers/concerns/fishrappr/catalog.rb
- ensure that all page fields are included in issue data (sigh)
- separate issue `:id` from `:barcode`
- adjust PDF downloader accordingly
- have ZIP create a folder for the issue data
> fix issue data to include issue id vs. barcode + page identifiers

- app/helpers/facets_helper.rb
- app/views/catalog/_facet_layout.html.erb
1. Updated sr-only span in def render_selected_facet_value(facet_field, item) to clarify what is being removed.
2. Added title attr to def render_facet_count(num, options = {}) to explain what the number represents.
> add title to facet numbers for screen readers

- app/controllers/concerns/fishrappr/catalog.rb
- app/helpers/application_helper.rb
- app/helpers/zzzzzz_helper.rb
- app/views/catalog/show.html.erb
- track `page` as part of the search session
- track search session for `browse`
- remove hacking of `params` to set different views for `index` vs. `browse`
- tweak `show.html.erb` so that the navbar always shows regardless of whether there's an active search session
> unify index/browse handling for current_search_params

- app/controllers/application_controller.rb
- app/controllers/catalog_controller.rb
- app/controllers/concerns/fishrappr/catalog.rb
- app/controllers/concerns/fishrappr/context.rb
- app/controllers/static_controller.rb
Fixes issue where help/contact pages would balk because there was no publication object.
> move setup_publication to context concern

- app/assets/stylesheets/modules/viewer.scss
- app/helpers/application_helper.rb
- app/views/catalog/_home_header_navbar.html.erb
- app/views/catalog/_show_header_default.html.erb
- app/views/shared/_header_navbar.html.erb
- config/routes.rb
- redirects the root request to the default publication (currently: `the-michigan-daily`; planned: `midaily`)
- updates the header to use `publication_root_url`
- (minor template and CSS fixes)
> set up routes to handle http://digital.bentley.umich.edu/midaily

- app/assets/stylesheets/blacklight.scss
- app/assets/stylesheets/bootstrap-variables.scss
- app/assets/stylesheets/modules/custom.scss
- app/assets/stylesheets/modules/grid.scss
- app/helpers/facets_helper.rb
- app/views/catalog/_constraints_element.html.erb
- app/views/catalog/_document.html.erb
- app/views/catalog/_home_text.html.erb
- app/views/kaminari/blacklight/_first_page.html.erb
- app/views/kaminari/blacklight/_gap.html.erb
- app/views/kaminari/blacklight/_last_page.html.erb
- app/views/kaminari/blacklight/_next_page.html.erb
- app/views/kaminari/blacklight/_page.html.erb
- app/views/kaminari/blacklight/_paginator.html.erb
- app/views/kaminari/blacklight/_prev_page.html.erb
- config/locales/blacklight.en.yml
**update index page style to match zeplin but**
1. No fix for empty results page content or graph yet.
2. No fix for responsiveness yet.
3. I'm not happy with the look of the li.active in the bottom pagination yet.
4. We could switch over to all "open sans" font but this still has Helvetica in places.
5. No icon changes yet.
> update index page style to match zeplin

- app/assets/stylesheets/fishrappr.scss
- app/assets/stylesheets/modules/contacts.scss
- app/assets/stylesheets/modules/custom.scss
- app/controllers/contacts_controller.rb
- app/models/contact.rb
- app/views/catalog/_image_viewer_toolbar_bottom.html.erb
- app/views/catalog/show.html.erb
- app/views/contacts/new.html.erb
- app/views/contacts/success.html.erb
- app/views/layouts/application.html.erb
- config/locales/en.yml
- tweak contact form styles to match zepplin mockups
- support prompts for different contact types
- allow contact form type to be initialized from URL parameters
- wire the "report problems" on the image viewer
- referer URLs are tracked for all contact submissions
> contact form updates

- app/assets/stylesheets/modules/viewer.scss
- app/views/catalog/_image_viewer_toolbar_bottom.html.erb
- app/views/catalog/_show_header_default.html.erb
- app/views/catalog/show.html.erb
- add report a problem link to bottom of page viewer sidebar
- sidebar better matches zepto
- tabloid note links to image viewer help # tabloid-pages
> address issues 249 and 199

- app/helpers/application_helper.rb
- app/views/catalog/_document_share_metadata.html.erb
On the page titles have a bit of structure so they become shorter in narrower contexts. That gets in the way of facebook/twitter harvesting.
> ensure that titles can be gotten as plain text

- app/assets/javascripts/page_image_viewer.js
- app/helpers/application_helper.rb
- app/services/repository_service.rb
Tweaking requests to use Image API path that's tuned for only serving small images.
> use /tile/ path in image api for guanranteed-to-be-smaller images

- app/controllers/concerns/fishrappr/context.rb
- app/helpers/blacklight_helper.rb
- config/locales/en.yml
Override blacklight template to key `application_name` based on the publication slug.
Aside: we could have used `publication.title` but `midaily` has a title of _The Michigan Daily_, not _Michigan Daily Digital Archives_.
That publication title is re-used in the PDFs to refer to the source publication, not the digital archives, so it's probably best to keep them separate.
> Set application_name based on publication

- app/assets/stylesheets/modules/custom.scss
- app/views/contacts/success.html.erb
- config/locales/en.yml
- fixes some obvious problem with contacts success page
- restructured the success page to match the other help pages
- small adjustment to the .help-sbar css seemed to improve side bar positioning a bit
- adds .contacts-success .help-sbar { margin-top: auto; } to fix position of sbar on that page
> fix problems with contact success page
